version: '3'

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
  gen-env:
    cmds:
      - bash -c 'printf "USER=%s\nUID=%s\nGID=%s\nGROUP=%s\n" "$USER" "$(id -u)" "$(id -g)" "$(id -gn)" > .env'
    silent: true
  build.gpu:
    desc: Build docker image with gpu support
    cmd: docker compose build dwpp_test_gpu --build-arg USER_ID=$(id -u)
    silent: true
  build.jazzy.gpu:
    desc: Build docker image with gpu support, jazzy version
    deps: [gen-env]
    cmd: docker compose build dwpp_test_jazzy_gpu
    silent: true
  build.cpu:
    desc: Build docker image with cpu support
    cmd: docker compose build dwpp_test_cpu --build-arg USER_ID=$(id -u)
    silent: true
  run.jazzy.gpu:
    desc: Run docker container with gpu support
    cmd: docker compose run --rm dwpp_test_jazzy_gpu
    silent: true
  run.gpu:
    desc: Run docker container with gpu support
    cmd: docker compose run --rm dwpp_test_gpu
    silent: true
  run.cpu:
    desc: Run docker container with cpu support
    cmd: docker compose run --rm dwpp_test_cpu
    silent: true
  ruff:
    desc: Run ruff
    cmds:
      - ruff check --fix
      - ruff format
    silent: true
  type-check:
    desc: Check type by pyright
    cmds:
      - uv tool run pyright
    silent: true
  push:
    desc: git push
    cmds:
      - git add .
      - git commit
      - git push origin $(git rev-parse --abbrev-ref HEAD)
    silent: false
  pull:
    desc: git pull
    cmd: git pull origin $(git rev-parse --abbrev-ref HEAD)
    silent: false
